### ISSUE TITLE
api不能用了！！！！

### ISSUE THREAD

**Issue by edsionzhang1** [zxlie/WeixinApi#40]
试了一下作者的demo页面，也不能用了。是微信禁止了这个api吗。希望作者能尽快给出新的的api

**Comment by Asher-Tan** [comment]
微信这么一变，挺伤的。还不知什么时候会正式放出接口。

**Comment by liaol** [comment]
@mgcnrx11 域名被屏蔽了 可能是未备案或者分享频率太高

**Comment by mgcnrx11** [comment]
@liaol

域名是备案了的，但分享频率太高也有可能？我们之前在做测试而已啊，应该不会很高的

**Comment by zxlie** [comment]
简单升级了一下，暂时能支持Android下的正常分享，请受到影响的用户更新一下吧，具体参考：http://www.baidufe.com/item/6d0ca3449bfdb612f3ac.html

**Comment by liaol** [comment]
@mgcnrx11 我遇到过这问题 准备用一堆域名替换吧

**Comment by mani95lisa** [comment]
@zxlie 刚看到这个可以正常使用，有朋友能看出来是为什么吗？里面好乱我都看不到微信分享的调用信息，难道是通过服务器随机生成的符合微信标准的页面？ http://sla.sh.1251246865.cee.myqcloud.com/ceshi/?wid=194&t=1420368049&from=groupmessage&isappinstalled=0

**Comment by zxlie** [comment]
对iOS做了一下简单升级，目前支持分享文字和图片的设置，各位酌情升级吧：https://github.com/zxlie/WeixinApi#3%E5%AF%B9ios%E7%89%88%E6%9C%AC%E8%BF%9B%E8%A1%8C%E7%AE%80%E5%8D%95%E6%94%AF%E6%8C%81

没有什么太好的办法，不过据小道消息，微信官方正在升级weixin-api-sdk，但愿春节前能放出来吧，到时候大家都可以直接用官方提供的了，万事大吉，我只能帮大家到这儿了。God Bless All！

**Comment by blueszhao** [comment]
@zxlie  Thanks!

**Comment by owen26** [comment]
@zxlie 说的没错，据小道消息微信正在做官方的JS API，基本上是走和公众号API类似的路线，要通过APPID和APPSECRET拿到code，通过code获取token，通过token加时间戳和随机字符串SHA1算出signature签名，然后用签名和APPID（目前不知道此ID是公众号ID还是开放平台ID）来请求官方的JS API给予各种权限。还要绑定URL，不是随便写个网页就能调用的了。

反正是挺麻烦的，基于安全考虑，肯定一套算法都要配合使用后端技术比如PHP、asp.net生成签名，不再是纯前端html就可以搞定的了。

下面是新api的大致语法：

```javascript
//初始化配置
wx.config({
	debug: true, // 调试模式,会打印所有调用返回信息
	appId: '', 
	timestamp: 0, // 时间戳
	nonceStr: '', // 随机串
	signature: '',// 签名，参考我上面给出的解释
	jsApiList: [] // 请求权限
});
```

```javascript
//分享朋友圈
wx.onMenuShareTimeline({
    title: '', // 分享标题
    link: '', // 分享链接
    imgUrl: '', // 分享图标
    success: function () { }, //成功回调
    cancel: function () { }, //失败回调
});
```

**Comment by fangge** [comment]
@owen26 sad 不过有总比没有好

**Comment by zxlie** [comment]
我能为大家做的，也就这些了，各位酌情升级：http://www.baidufe.com/item/1a46c018b12dd99057a3.html

**Comment by gaoguoxin** [comment]
万分感激

**Comment by naoyeye** [comment]
留名

**Comment by subying** [comment]
已经做得很不错了，现在完善的方法只能等微信那边。

**Comment by subying** [comment]
@zxlie 居然没发现一直用的web前端助手也是你的作品...

**Comment by hymcn** [comment]
万分感激！ @zxlie IOS 微信6.0.2分享朋友圈没有图片

**Comment by stupidtang** [comment]
前天还行的，，，最近升6.1又不行了吗。。。？？
