### ISSUE TITLE
微信6.0.2解决方案汇总!

### ISSUE THREAD

**Issue by edsionzhang1** [zxlie/WeixinApi#44]
目前的解决方案汇总:

链接：https://github.com/blueszhao/wechat/wiki  
解决的问题：自定义分享图片、标题、链接
thanks @blueszhao

另外的解决方案：
http://blog.csdn.net/im_kk/article/details/42435471
这个也是不错的解决方法！

欢迎大家积极跟帖解决方案，方便大家~~

集中讨论微信群
![image](https://cloud.githubusercontent.com/assets/8691524/5657626/5ac5f946-972c-11e4-8c95-3e1667fa26f3.png)

**Comment by zxlie** [comment]
对iOS做了下简单兼容，详情参考：https://github.com/zxlie/WeixinApi#3%E5%AF%B9ios%E7%89%88%E6%9C%AC%E8%BF%9B%E8%A1%8C%E7%AE%80%E5%8D%95%E6%94%AF%E6%8C%81

**Comment by edsionzhang1** [comment]
@zxlie 谢谢不懈的努力。。。太感动了

**Comment by wanggj** [comment]
貌似这个方案不向下兼容，改完后6.0.2可以，6.0.0不行了

**Comment by lanrion** [comment]
二维码已经过期。

**Comment by lanrion** [comment]
自定义链接，如果是从朋友圈或者朋友会话框点击进入server端，会有特定的微信的参数，可以再做一次重定向。

**Comment by lanrion** [comment]
@blueszhao “群聊人数已达到上限，无法加入”。

**Comment by zxlie** [comment]
我能为大家做的，也就这些了，各位酌情升级：http://www.baidufe.com/item/1a46c018b12dd99057a3.html

**Comment by huixisheng** [comment]
[官方Api已开放](http://mp.weixin.qq.com/wiki/7/aaa137b55fb2e0456bf8dd9148dd613f.html)
