### ISSUE TITLE
IOS下收藏报错

### ISSUE THREAD

**Issue by coolguy001tv** [zxlie/WeixinApi#47]
RT,即使是你给的DEMO，在分享的时候仍然会提示出错。
大致错误信息如下：
额，代码有错。。。
错误信息：TypeError: 'undefined' is not a function(evaluating 'j.generalShare(k,function(){})')
出错文件:..../WeixinApi.js
出错位置：(这里的信息根据不同的情况，抱错行不一样)

如果关闭调试模式，收藏不会报错，但是也不会收藏成功。
IPHONE4和IPHONE5都有一样的问题

**Comment by Goo-** [comment]
您好！您的邮件我已收到,我会及时查收回复！
