### ISSUE TITLE
【微信 6.1】发送给朋友 和 分享到朋友圈 没有响应了

### ISSUE THREAD

**Issue by c9n** [zxlie/WeixinApi#56]
感觉升级之后，分享接口彻底挂掉了，不晓得其他人发现这个问题了没。

**Comment by c9n** [comment]
只有 ImagePreview 还可以调用

**Comment by leohgbs** [comment]
低版本(android)使用该插件，高版本(6.1)使用微信JS-SDK方法不会出问题

**Comment by iamike** [comment]
是啊，好像都没反映了

**Comment by fangge** [comment]
@leohgbs ios的6.1用腾讯自己做的js sdk分享还是会有问题
http://demo.open.weixin.qq.com/jssdk/

**Comment by leohgbs** [comment]
＠fangge 把debug设为true，自定义分享的内容在wx.ready中设置

**Comment by max1238** [comment]
没有高级接口如何用啊

**Comment by max1238** [comment]
ios 6.1中点击分享朋友是没有反应的

**Comment by c9n** [comment]
@max1238 6.1 必须认证公众号，设置安全域名，使用官方sdk

**Comment by phoenixg** [comment]
我也是，这个SDK在6.1版本就 不能用了？

**Comment by feikeq** [comment]
已经不能用了,只能用微信官方的JSSDK了.

**Comment by sokoo** [comment]
被官方的js搞的代码看着一团糟，在都是6.1的微信版本下，Android不能使用官方的自定义分享，可以使用WeixinApi v4.3实现自定义分享，而IOS能使用官方的自定义分享，不能使用WeixinApi v4.3。故代码里实现了两套通过useragent判断设备case加载不同脚本，简直崩溃！！！

**Comment by itime** [comment]
android v6.1,前几天还能用，最近发送给朋友不能用了，停一会又跳回原页面

**Comment by leohgbs** [comment]
所有配置ok
ios出现这样一个问题：扫码进入的不能触发相关事件

**Comment by leohgbs** [comment]
具体情况：
　通过扫一扫进入，base授权(或者高级授权)之后，JS-SDK config均显示OK
　直接通过微信内部链接进入，base授权(或高级授权)之后，config显示OK

    以上情况均，iPhone自定义分享均无法使用

　通过android分享给iPhone，所有一切恢复正常

hack方案：
　授权回来，强制刷新一次，OK

不清楚为什么会这样

**Comment by itime** [comment]
可能是手机问题，重装了微信还是不行，装回旧版本也不行，最后重新刷机，分享又可以用了

**Comment by leohgbs** [comment]
iPhone 都存在这个问题，android没有

**Comment by leohgbs** [comment]
今天才出现这个问题，至少我是今天遇到这个问题，以前同样操作没有任何问题

**Comment by hojas** [comment]
官方的api需要服务器端支持或验证码？

**Comment by c9n** [comment]
@hojas https://github.com/c9n/weixin-js-api

**Comment by hojas** [comment]
@c9n 添加了JS接口安全域名多久才生效啊？

**Comment by c9n** [comment]
@hojas 只要是备案过的域名 立马就生效了
